<?xml version="1.0"?>
<!-- DJI Matrice 100 Quadrotor -->
<robot name="dji" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="30" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="0.2" /> <!-- DJI height -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find dji_description)/urdf/dji.gazebo" />
  <!-- Import colors -->
  <xacro:include filename="$(find dji_description)/urdf/materials.xacro" />
  
  <!-- DJI Body Link -->
  <link name="dji_link">
    <collision name="dji_body_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	    <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision> 

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	    <!--<box size="${width} ${width} ${height}"/> -->
	    <mesh filename="package://dji_description/meshes/dji_matrice_100_05.stl"/> 
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
<!-- 
    <sensor name='dji_body_collision' type='contact'>
      <contact>
        <collision>collision</collision>
      </contact>
    </sensor> -->

  </link>

  <joint name="hokuyo_joint" type="fixed">
    <parent link="dji_link"/>
    <child link="hokuyo_link"/>
    <origin xyz="0.0 0 ${height/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
	    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <!-- <visual> -->
      <!-- <origin xyz="0 0 0.0" rpy="0 0 0"/> -->
      <!-- <geometry> -->
        <!-- <mesh filename="package://dji_description/meshes/hokuyo_utm_30lx.dae"/>  -->
        <!--<box size="0.1 0.1 0.1"/>-->
      <!-- </geometry> -->
    <!-- </visual> -->

    <!-- <inertial> -->
      <!-- <mass value="0.1" /> -->
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <!-- <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" /> -->
    <!-- </inertial> -->
  </link>

</robot>
